version: '2.4'
services:
    app:
        build: .
        volumes:
            - ./:/app
            # - $GOPATH/pkg/mod/cache:/go/pkg/mod/cache
        working_dir: /app
        # env_file:
        #     - .env
        ports:
            - 8080:8080
